[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Makes the gears not have duplicates oh my god its finally happening
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'elseif not (G.GAME.used_jokers[v.key] and not next(find_joker("Showman"))) and'
position = "at"
payload = '''
elseif not (G.GAME.used_jokers[v.key] and not next(find_joker("Showman")) and v.set ~= "Gear") and
'''
match_indent = true